# Generated by Django 2.2.2 on 2019-07-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(max_length='10', verbose_name='Celular'),
        ),
    ]
